name: Build on Pr

on:
  pull_request:
    branch:
      - master


jobs:
  build:
    runs-on: ubantu-latest
    steps:
      - users: actions/checkout@v3
      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Generate prisma client
        run: npm run db:generate
        
      - name: Run Build
        run: npm run build